version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    expose:
      - "8000"
    restart: unless-stopped

  admin:
    build: ./backend
    container_name: admin
    env_file: .env
    ports:
      - "127.0.0.1:8080:8080"  # TYLKO localhost — dostęp wyłącznie przez SSH tunnel
    command: uvicorn backend.admin_app:app --host 0.0.0.0 --port 8080
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80" # Tylko ten port wystawiamy na świat!
    depends_on:
      - backend
    restart: unless-stopped
