version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80" # Tylko ten port wystawiamy na świat!
    depends_on:
      - backend
    restart: unless-stopped
